version: '3'

services:

  loltimeflashbackend:
    container_name: loltimeflashbackend
    env_file: ./.env
    build:
      context: . 
      dockerfile: ./Dockerfile  
    ports:
      - "${PORT}:${PORT}"
    networks:
      - netloltimeflash

volumes:
  loltimeflashbackdata:
networks:
  netloltimeflash:
    name: netloltimeflash
    external: true
